In [1]:
import numpy as np
import pandas as pd
import os
import torch
from torchvision import tv_tensors
import matplotlib.pyplot as plt
import pydicom
from PIL import Image
from tqdm import tqdm
import pickle
from copy import deepcopy

DATA_PATH = "D:/ML/RSNA2024"

In [2]:
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)

print(f"Using {device} device")

Using cuda device

In [3]:
# CLASSES = ['L1/L2', 'L2/L3', 'L3/L4', 'L4/L5', 'L5/S1']
CLASSES = ['L5/S1', 'Other']
OTHER_CLASSES = ['L4/L5', 'L3/L4', 'L2/L3', 'L1/L2' ]
ALL_CLASSES=['L5/S1', 'L4/L5', 'L3/L4', 'L2/L3', 'L1/L2' ]
values = CLASSES
keys = np.arange(0,len(CLASSES))
IntToClass= dict(zip(keys, values))

classToInt = dict(zip(values, keys))

In [4]:
df = pd.read_csv(os.path.join(DATA_PATH, "train.csv"))
df = df.fillna("Normal/Mild")


dfDescr = pd.read_csv(os.path.join(DATA_PATH, "train_series_descriptions.csv"))
uniqueSeriesDescr = np.array(['Sagittal T2/STIR', 'Sagittal T1', 'Axial T2'])
dfDescr.set_index("study_id", inplace=True)
uniqueStudIds = dfDescr.index.unique()

dfCoord = pd.read_csv(os.path.join(DATA_PATH, "train_label_coordinates.csv"))

In [5]:
dfDescr.head()

           series_id series_description
study_id
4003253    702807833   Sagittal T2/STIR
4003253   1054713880        Sagittal T1
4003253   2448190387           Axial T2
4646740   3201256954           Axial T2
4646740   3486248476        Sagittal T1

In [6]:
dfDescr.loc[178041181]

            series_id series_description
study_id
178041181   530141745           Axial T2
178041181  1778659905           Axial T2
178041181  2197800987           Axial T2
178041181  2495441739   Sagittal T2/STIR
178041181  3904103024        Sagittal T1

In [7]:
from DicomDataset import *

### Position

The x, y, and z coordinates of the upper left hand corner (center of the first voxel transmitted) of the image, in mm

### Orientation

This means that the dicom world (or patient) coordinate system is LPS:

X is Right to Left (RL)
Y is Anterior to Posterior (AP)
Z is Inferior to Superior (IS)

The Image Orientation (Patient) dicom tag is (0020,0037), and is defined as 6 elements: "Ax, Ay, Az, Bx, By, Bz".

When described as a 3x3 rotation matrix R, it's equivalent to:


$$
\left(\begin{array}{cc} 
A_x & B_x & 0\\
A_y & B_y & 0\\
A_z & B_z & 0\\
\end{array}\right)
$$ 

### Pixel Spacing

Physical distance in the patient between the center of each pixel, specified by a numeric pair - adjacent row spacing (delimiter) adjacent column spacing in mm.

-----

## Data Extraction Process

1. For all patients create PatientData
1. Get all sagittal scans
1. Process every slice with the vertebrae detector
1. For every level L
    1. Get all patches from bounding boxes @ level L (extend the boxes to get the spinal canal and foramina!)
    1. Use a random slice where all levels can be seen to extract the axial slices @ level L. Also center crop them.

--> For every patient the data consists of separate data for every level

```json
{
    "L1/L2":
        {"sagittalPatches": [...], "axialSlices":[...]},
    "L2/L3":
        {"sagittalPatches": [...], "axialSlices":[...]},
    "L3/L4":
        ...
}

```

In [8]:
def createScanMapping(studyId):
    seriesIds = dfDescr.loc[studyId]["series_id"].to_numpy()
    seriesDescriptions = dfDescr.loc[studyId]["series_description"].to_numpy()
    scanMapping = []
    for seriesIndex,serId in enumerate(seriesIds):
        seriesDescr = seriesDescriptions[seriesIndex]
        if "Sagittal" in seriesDescr:
            orient = OrientationType.Sagittal
        elif "Axial" in seriesDescr or "Transversal" in seriesDescr:
            orient = OrientationType.Axial
        elif "Frontal" in seriesDescr:
            orient = OrientationType.Frontal
        else:
            orient = OrientationType.Unknown
        folder = os.path.join(DATA_PATH, f"train_images/{studyId}/{serId}")
        scanMapping.append((orient, folder))
    return scanMapping

In [9]:
vertebraeDetector = torch.load(os.path.join(DATA_PATH, "VertebraeDetectorBinary_epoch129_mAP0.5763.pth"))
vertebraeDetector.to(device)
vertebraeDetector.eval()

C:\Users\manue\AppData\Local\Temp\ipykernel_29020\3410995556.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  vertebraeDetector = torch.load(os.path.join(DATA_PATH, "VertebraeDetectorBinary_epoch129_mAP0.5763.pth"))

RetinaNet(
  (backbone): BackboneWithFPN(
    (body): IntermediateLayerGetter(
      (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
      (layer1): Sequential(
        (0): Bottleneck(
          (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU(inplace=True)
          (downsample): Sequential(
            (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (1): Bottleneck(
          (conv1): Conv2d(256, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU(inplace=True)
        )
        (2): Bottleneck(
          (conv1): Conv2d(256, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU(inplace=True)
        )
      )
      (layer2): Sequential(
        (0): Bottleneck(
          (conv1): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
          (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv3): Conv2d(128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU(inplace=True)
          (downsample): Sequential(
            (0): Conv2d(256, 512, kernel_size=(1, 1), stride=(2, 2), bias=False)
            (1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (1): Bottleneck(
          (conv1): Conv2d(512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv3): Conv2d(128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU(inplace=True)
        )
        (2): Bottleneck(
          (conv1): Conv2d(512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv3): Conv2d(128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU(inplace=True)
        )
        (3): Bottleneck(
          (conv1): Conv2d(512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv3): Conv2d(128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU(inplace=True)
        )
      )
      (layer3): Sequential(
        (0): Bottleneck(
          (conv1): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
          (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv3): Conv2d(256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU(inplace=True)
          (downsample): Sequential(
            (0): Conv2d(512, 1024, kernel_size=(1, 1), stride=(2, 2), bias=False)
            (1): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (1): Bottleneck(
          (conv1): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv3): Conv2d(256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU(inplace=True)
        )
        (2): Bottleneck(
          (conv1): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv3): Conv2d(256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU(inplace=True)
        )
        (3): Bottleneck(
          (conv1): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv3): Conv2d(256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU(inplace=True)
        )
        (4): Bottleneck(
          (conv1): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv3): Conv2d(256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU(inplace=True)
        )
        (5): Bottleneck(
          (conv1): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv3): Conv2d(256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU(inplace=True)
        )
      )
      (layer4): Sequential(
        (0): Bottleneck(
          (conv1): Conv2d(1024, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
          (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv3): Conv2d(512, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(2048, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU(inplace=True)
          (downsample): Sequential(
            (0): Conv2d(1024, 2048, kernel_size=(1, 1), stride=(2, 2), bias=False)
            (1): BatchNorm2d(2048, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (1): Bottleneck(
          (conv1): Conv2d(2048, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv3): Conv2d(512, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(2048, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU(inplace=True)
        )
        (2): Bottleneck(
          (conv1): Conv2d(2048, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv3): Conv2d(512, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(2048, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU(inplace=True)
        )
      )
    )
    (fpn): FeaturePyramidNetwork(
      (inner_blocks): ModuleList(
        (0): Conv2dNormActivation(
          (0): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1))
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1))
        )
        (2): Conv2dNormActivation(
          (0): Conv2d(2048, 256, kernel_size=(1, 1), stride=(1, 1))
        )
      )
      (layer_blocks): ModuleList(
        (0-2): 3 x Conv2dNormActivation(
          (0): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        )
      )
      (extra_blocks): LastLevelP6P7(
        (p6): Conv2d(2048, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
        (p7): Conv2d(256, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
      )
    )
  )
  (anchor_generator): AnchorGenerator()
  (head): RetinaNetHead(
    (classification_head): RetinaNetClassificationHead(
      (conv): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (1): GroupNorm(32, 256, eps=1e-05, affine=True)
          (2): ReLU(inplace=True)
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (1): GroupNorm(32, 256, eps=1e-05, affine=True)
          (2): ReLU(inplace=True)
        )
        (2): Conv2dNormActivation(
          (0): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (1): GroupNorm(32, 256, eps=1e-05, affine=True)
          (2): ReLU(inplace=True)
        )
        (3): Conv2dNormActivation(
          (0): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (1): GroupNorm(32, 256, eps=1e-05, affine=True)
          (2): ReLU(inplace=True)
        )
      )
      (cls_logits): Conv2d(256, 18, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (regression_head): RetinaNetRegressionHead(
      (conv): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (1): GroupNorm(32, 256, eps=1e-05, affine=True)
          (2): ReLU(inplace=True)
        )
        (1): Conv2dNormActivation(
          (0): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (1): GroupNorm(32, 256, eps=1e-05, affine=True)
          (2): ReLU(inplace=True)
        )
        (2): Conv2dNormActivation(
          (0): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (1): GroupNorm(32, 256, eps=1e-05, affine=True)
          (2): ReLU(inplace=True)
        )
        (3): Conv2dNormActivation(
          (0): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (1): GroupNorm(32, 256, eps=1e-05, affine=True)
          (2): ReLU(inplace=True)
        )
      )
      (bbox_reg): Conv2d(256, 36, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
  )
  (transform): GeneralizedRCNNTransform(
      Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
      Resize(min_size=(800,), max_size=1333, mode='bilinear')
  )
)

In [10]:
import matplotlib.patches as patches


def plotImageWithAnnot(im, target, filename=None):
    fig, ax = plt.subplots()
    imsh = ax.imshow(im)
    fig.colorbar(imsh, ax=ax)

    for idx,b in enumerate(target["boxes"]):
        b = b.numpy()
        rect = patches.Rectangle((b[0], b[1]), b[2]-b[0], b[3]-b[1], linewidth=1, edgecolor='r', facecolor='none')
        ax.add_patch(rect)
        plt.text(b[0], b[1]-4, IntToClass[target["labels"].numpy()[idx]], {"color":"red"})
    if filename:
        plt.title(filename)
        plt.tight_layout()
        plt.savefig(os.path.join(DATA_PATH, f"objDetExamples/{filename}.png"), dpi=120)
        plt.close()
    else:
        plt.show()

def plotImageWithBB(im, boundingBoxes, labels=None, filename=None):
    fig, ax = plt.subplots()
    imsh = ax.imshow(im)
    fig.colorbar(imsh, ax=ax)

    for idx,b in enumerate(boundingBoxes):
        b = b.numpy()
        rect = patches.Rectangle((b[0], b[1]), b[2]-b[0], b[3]-b[1], linewidth=1, edgecolor='r', facecolor='none')
        ax.add_patch(rect)
        if not labels==None:
            plt.text(b[0], b[1]-4, IntToClass[labels.numpy()[idx]], {"color":"red"})
    if filename:
        plt.title(filename)
        plt.tight_layout()
        plt.savefig(os.path.join(DATA_PATH, f"objDetExamples/{filename}.png"), dpi=120)
        plt.close()
    else:
        plt.show()

In [11]:
def filterBoundingBoxes(targets, threshold=0.7):
    if type(targets)!=list:
        raise ValueError("targets has to be a list of dictionaries containing {'boxes':..., 'scores':..., 'labels':...}")
    filteredBB=[]
    for target in targets:
        scores = target["scores"].detach().cpu().numpy()
        boxes = target["boxes"].detach().cpu().numpy()
        labels = [IntToClass[el] for el in target["labels"].detach().cpu().numpy()]

        filtered={}
        newScores=[]

        for c in CLASSES:
            classIdxs = np.argwhere(np.array(labels)==c).flatten()
            if classIdxs.shape[0]==0:
                continue
            highestScore  = scores[classIdxs][0]
            if highestScore>threshold:
                filtered[c] = boxes[classIdxs[0]]
                newScores.append(highestScore)
        filteredBB.append({"filteredBB": filtered, "scores": newScores})
    return filteredBB



# testTar =[{'boxes': torch.tensor([[277.0559, 480.4082, 342.5710, 546.4760],
#           [246.1063, 421.0921, 322.0190, 465.9918],
#           [232.9959, 355.6693, 310.8026, 393.1955],
#           [235.5022, 282.2717, 309.8636, 314.1367],
#           [240.6923, 209.3363, 311.7209, 240.0908],
#           [240.8825, 210.6963, 311.3056, 239.0509],
#           [366.7859, 303.0891, 401.7643, 343.1634],
#           [244.8488, 142.8043, 313.3584, 171.8768],
#           [233.2152, 355.9161, 310.8337, 393.3716],
#           [277.0559, 480.4082, 342.5710, 546.4760],
#           [245.6599, 420.8578, 322.0050, 465.7909],
#           [362.5488, 364.8280, 410.1449, 413.4319],
#           [366.9376, 302.8406, 401.8413, 342.6856],
#           [366.8237, 302.9432, 401.6767, 343.5234]]),
#   'scores': torch.tensor([1.0000, 0.9999, 0.9998, 0.9985, 0.8368, 0.4317, 0.3369, 0.1112, 0.0953,
#           0.0714, 0.0698, 0.0658, 0.0620, 0.0581]),
#   'labels': torch.tensor([4, 3, 2, 1, 0, 1, 3, 0, 1, 3, 2, 4, 4, 0])}]

# filterBoundingBoxes(testTar)

In [12]:
def filterBoundingBoxesBinary(targets, threshold=0.9):
    if type(targets)!=list:
        raise ValueError("targets has to be a list of dictionaries containing {'boxes':..., 'scores':..., 'labels':...}")
    filteredBB=[]
    for target in targets:
        scores = target["scores"].detach().cpu().numpy()
        boxes = target["boxes"].detach().cpu().numpy()
        labels = [IntToClass[el] for el in target["labels"].detach().cpu().numpy()]

        output={}
        outputScores=[]

        if not "L5/S1" in labels:
            # No L5 found -> no assignment of all the other vertebrae possible
            filteredBB.append({})
            continue

        #Get L5/S1 with the highest score
        classIdxs = np.argwhere(np.array(labels)=="L5/S1").flatten()
        l5Scores  = np.array(scores)[classIdxs]
        l5Boxes = np.array(boxes)[classIdxs]
        highestL5ScoreIdx = np.argmax(l5Scores).flatten()
        l5Box = l5Boxes[highestL5ScoreIdx][0]
        l5Score = l5Scores[highestL5ScoreIdx]
        if l5Score<threshold:
            filteredBB.append({})
            continue
        output["L5/S1"] = {'filteredBB': l5Box, 'score': l5Score[0]}

        #Get all Other vertebrae with score > threshold
        classIdxs = np.argwhere((np.array(labels)=="Other") & (np.array(scores)>threshold)).flatten()
        otherBoxes = np.array(boxes)[classIdxs]
        otherScores = np.array(scores)[classIdxs]
        
        #Sort ascending by difference in y direction of the boxes to the L5 Box 
        yDistanceToL5 = [l5Box[3] - el[3] for el in otherBoxes]
        sortedIdxs = np.argsort(yDistanceToL5)
        otherBoxesSorted = otherBoxes[sortedIdxs]
        otherScoresSorted = otherScores[sortedIdxs]
        yDistanceToL5Sorted = np.array(yDistanceToL5)[sortedIdxs]


        levelIdx=0
        for i,otherBox in enumerate(otherBoxesSorted):
            if len(output.keys())==len(ALL_CLASSES):
                #Found all
                break
            if yDistanceToL5Sorted[i]<20:
                #If the other box is below or very close to L5, assume its detected as L5/S1 and another one simultaneously
                continue
            output[OTHER_CLASSES[levelIdx]]={'filteredBB': otherBox, 'score': otherScoresSorted[i]}
            levelIdx += 1
        filteredBB.append(output)
    return filteredBB





testTar =[{'boxes': torch.tensor([[277.0559, 480.4082, 342.5710, 546.4760],
          [246.1063, 421.0921, 322.0190, 465.9918],
          [232.9959, 355.6693, 310.8026, 393.1955],
          [235.5022, 282.2717, 309.8636, 314.1367],
          [240.6923, 209.3363, 311.7209, 240.0908],
          [240.8825, 210.6963, 311.3056, 239.0509],
          [366.7859, 303.0891, 401.7643, 343.1634],
          [244.8488, 142.8043, 313.3584, 171.8768],
          [233.2152, 355.9161, 310.8337, 393.3716],
          [277.0559, 480.4082, 342.5710, 546.4760],
          [245.6599, 420.8578, 322.0050, 465.7909],
          [362.5488, 364.8280, 410.1449, 413.4319],
          [366.9376, 302.8406, 401.8413, 342.6856],
          [366.8237, 302.9432, 401.6767, 343.5234]]),
  'scores': torch.tensor([1.0000, 0.9999, 0.9998, 0.9985, 0.8368, 0.4317, 0.3369, 0.1112, 0.0953,
          0.0714, 0.0698, 0.0658, 0.0620, 0.0581]),
  'labels': torch.tensor([0,0,1,1,1,1,1,1,1,1,1,1,1,1])}]

filterBoundingBoxesBinary(testTar)

[{'L5/S1': {'filteredBB': array([277.0559, 480.4082, 342.571 , 546.476 ], dtype=float32),
   'score': 1.0},
  'L4/L5': {'filteredBB': array([232.9959, 355.6693, 310.8026, 393.1955], dtype=float32),
   'score': 0.9998},
  'L3/L4': {'filteredBB': array([235.5022, 282.2717, 309.8636, 314.1367], dtype=float32),
   'score': 0.9985},
  'L2/L3': {'filteredBB': array([240.6923, 209.3363, 311.7209, 240.0908], dtype=float32),
   'score': 0.8368}}]

In [13]:
def extractPatch(im:np.array, bb, extensionFactor=0.0):
    # bb format: x1,y1,x2,y2
    if len(im.shape)!=2:
        raise ValueError(f"im has to be of shape (width, height) instead of {im.shape}")
    bbExt = [*bb]
    if extensionFactor>0:
        bbExt[0], bbExt[1] = np.clip(bbExt[0]*(1-extensionFactor), 0, im.shape[1]), np.clip(bbExt[1]*(1-extensionFactor), 0, im.shape[1])
        bbExt[2], bbExt[3] = np.clip(bbExt[2]*(1+extensionFactor), 0, im.shape[0]), np.clip(bbExt[3]*(1+extensionFactor), 0, im.shape[0])
    bbExt = [int(np.round(el)) for el in bbExt]
    # np array has height x width !
    return im[bbExt[1]:bbExt[3], bbExt[0]:bbExt[2]]

def extendBoundingBox(im:np.array, bb, extensionFactor=0.0):
    # bb format: x1,y1,x2,y2
    if len(im.shape)!=2:
        raise ValueError(f"im has to be of shape (width, height) instead of {im.shape}")
    bbExt = [*bb]
    if extensionFactor>0:
        bbExt[0], bbExt[1] = np.clip(bbExt[0]*(1-extensionFactor), 0, im.shape[1]), np.clip(bbExt[1]*(1-extensionFactor), 0, im.shape[1])
        bbExt[2], bbExt[3] = np.clip(bbExt[2]*(1+extensionFactor), 0, im.shape[0]), np.clip(bbExt[3]*(1+extensionFactor), 0, im.shape[0])
    bbExt = [int(np.round(el)) for el in bbExt]
    return bbExt

In [14]:
import plotly.graph_objs as go
import plotly.io as pio

def Visualize3DPointsAndSlices(points_list, colors=None, sliceList:list[Slice]=None):
    """
    Visualizes multiple lists of 3D points and optionally adds 3D planes representing slices, each with a different color,
    in an interactive 3D plot.

    Parameters:
        points_list (list of lists): A list of lists, where each sublist contains arrays of 3D points (x, y, z).
        colors (list of str): A list of colors for each set of points. Defaults to None, which uses a default color cycle.
        sliceList (list of dicts): A list of slices, where each slice is a dictionary with properties:
                                   'pixelSpacing' (2D vector), 'data' (2D numpy array), 
                                   'position' (3D vector), and 'orientation' (6D vector).
    """
    data = []
    
    # Generate a color palette if no colors are provided
    if colors is None:
        colors = ['blue', 'red', 'green', 'purple', 'orange', 'yellow', 'cyan', 'magenta']
    colorIdx=0
    
    # Loop through each list of points and corresponding color
    for i, points in enumerate(points_list):
        x_coords = [point[0] for point in points]
        y_coords = [point[1] for point in points]
        z_coords = [point[2] for point in points]
        
        scatter = go.Scatter3d(
            x=x_coords, 
            y=y_coords, 
            z=z_coords,
            mode='markers',
            marker=dict(
                size=5,
                color=colors[colorIdx % len(colors)],  # Cycle through the colors if more point sets than colors
                opacity=0.8
            ),
            name=f'Set {i+1}'  # Optional: Name each set
        )
        colorIdx += 1
        
        data.append(scatter)
    
    # Loop through each slice in the sliceList and add the plane
    if sliceList is not None:
        for idx, slice in enumerate(sliceList):
            # Extract the slice properties
            pixel_spacing = slice.pixelSpacing  # 2D vector
            position = np.array(slice.position)  # 3D vector
            orientation = np.array(slice.orientation)  # 6D vector (first 3 for row, next 3 for column)
            
            # Split the orientation into row and column vectors
            row_vector = orientation[:3]
            column_vector = orientation[3:]
            
            slice_height, slice_width = slice.data.shape  # Dimensions of the 2D slice (in pixels)
            
            # Calculate the four corners of the slice plane in 3D space
            top_left = position
            top_right = top_left + row_vector * slice_width * pixel_spacing[0]
            bottom_left = top_left + column_vector * slice_height * pixel_spacing[1]
            bottom_right = bottom_left + row_vector * slice_width * pixel_spacing[0]
            
            # Coordinates of the four corners
            x_coords = [top_left[0], top_right[0], bottom_right[0], bottom_left[0]]
            y_coords = [top_left[1], top_right[1], bottom_right[1], bottom_left[1]]
            z_coords = [top_left[2], top_right[2], bottom_right[2], bottom_left[2]]
            
            # Add the slice plane as a mesh to the plot
            plane = go.Mesh3d(
                x=x_coords,
                y=y_coords,
                z=z_coords,
                color=colors[colorIdx % len(colors)],  # Cycle through the colors if more slices than colors
                opacity=0.5,
                i=[0, 0, 0],
                j=[1, 2, 3],
                k=[2, 3, 1],
                name=f'Slice {idx+1}'  # Name each slice
            )
            
            data.append(plane)
    
    # Creating the layout for the plot
    layout = go.Layout(
        scene=dict(
            xaxis=dict(title='X Axis'),
            yaxis=dict(title='Y Axis'),
            zaxis=dict(title='Z Axis')
        ),
        margin=dict(l=0, r=0, b=0, t=0),  # Set margins
        legend=dict(x=0, y=1)  # Position the legend
    )
    
    fig = go.Figure(data=data, layout=layout)
    
    pio.show(fig)
    # return fig

Visualize3DPointsAndSlices(np.array([[[1,2,3]]]), sliceList=[Slice(np.random.random((50,50)), "123", "123", np.array([2,2,2]), np.array([0,1,0,0,0,1]), [0.5,0.5], [0.5,0.5])])

In [17]:
if os.path.exists(os.path.join(DATA_PATH,"./rawData.pkl")):
    with open(os.path.join(DATA_PATH,"./rawData.pkl"), "rb") as f:
        allData = pickle.load(f)
else:
    with torch.no_grad():
        allData = {}
        allPoints = {}
        for studyId in tqdm(uniqueStudIds):
            scanMapping = createScanMapping(studyId)
            patData = PatientData(scanMapping)
            sagScans = patData.getSagittalScans()
            allPoints[studyId] = {"axialPoints":[el.position for el in patData.getAxialScans()[0].slices], "sagittalPoints": [el.position for el in sagScans[0].slices]}
            sagittalPatches=dict(zip(ALL_CLASSES, [ [] for _ in range(len(ALL_CLASSES)) ]))
            axScans = patData.getAxialScans()
            axSlices=dict(zip(ALL_CLASSES, [ [] for _ in range(len(ALL_CLASSES)) ]))
            axSlicesExtracted = False
            
            for s in sagScans:
                for slice in s.slices:
                    # im = torch.tensor(slice.data.astype(np.float32)/255.0).to(device)
                    im = tv_tensors.Image(slice.data.astype(np.float32)/255.0).to(device)
                    targets = vertebraeDetector([im])
                    filteredBoundingBoxesList = filterBoundingBoxesBinary(targets, 0.95)
                    filteredBoundingBoxes = filteredBoundingBoxesList[0]
                    if len(filteredBoundingBoxes.keys())==0:
                        #No vertebrae visible
                        continue

                    # Get sagittal patches
                    for cl in filteredBoundingBoxes.keys():
                        bb = filteredBoundingBoxes[cl]["filteredBB"]
                        patch = extractPatch(im.detach().cpu().numpy()[0,:,:], bb, 0.1)
                        sagittalPatches[cl].append((patch*255).astype(np.uint8))

                    # Get axial slices
                    # allLevelsVisible = np.all([el in list(filteredBoundingBoxes.keys()) for el in CLASSES])
                    allLevelsVisible = np.all([el in list(filteredBoundingBoxes.keys()) for el in ALL_CLASSES])
                    axSlicesTemp = {}
                    if allLevelsVisible and not axSlicesExtracted:
                        #If there are bounding boxes of all 5 levels
                        #Get the slices that are in the range of that bounding box
                        for cl in filteredBoundingBoxes.keys():
                            bb = filteredBoundingBoxes[cl]["filteredBB"]
                            bb = extendBoundingBox(im.detach().cpu().numpy()[0,:,:], bb, 0.1)
                            startPos = slice.getWorldPosition(0,bb[3])
                            endPos = slice.getWorldPosition(0,bb[1])
                            for axScan in axScans:
                                axSlicesInRange = patData.getSlicesInRangeDirection(axScan, startPos, endPos, Direction.Z)
                                if len(axSlicesInRange)<1:
                                    #Didnt find enough slices -> continue
                                    # axSlicesTemp[cl] = []
                                    continue
                                else:
                                    axSlices[cl].append(axSlicesInRange)

                        # allLevelsDetected = np.all([el in list(axSlicesTemp.keys()) for el in ALL_CLASSES])
                        # if allLevelsDetected:
                        # axSlices = deepcopy(axSlicesTemp)
                        axSlicesExtracted=True
                        foundLevels = [len(axSlices[k])>=1 for k in list(axSlices.keys())]
            if not np.all(foundLevels) :
                print(f"Not all axial slices found for {studyId}: {np.array(list(axSlices.keys()))[foundLevels]}")
            allData[studyId] = {"axSlices": axSlices, "sagittalPatches": sagittalPatches}
                
        with open(os.path.join(DATA_PATH,"./rawData.pkl"), "wb") as f:
            pickle.dump(allData, f)

  1%|          | 17/1975 [00:30<1:05:27,  2.01s/it]

Not all axial slices found for 46494080: ['L5/S1' 'L4/L5' 'L3/L4']

  1%|          | 23/1975 [00:43<1:03:31,  1.95s/it]

Not all axial slices found for 60612428: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

  1%|▏         | 25/1975 [00:46<1:00:16,  1.85s/it]

Not all axial slices found for 64092030: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

  2%|▏         | 31/1975 [00:59<1:17:49,  2.40s/it]

Not all axial slices found for 74782131: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

  2%|▏         | 44/1975 [01:26<1:04:46,  2.01s/it]

Not all axial slices found for 97086905: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

  2%|▏         | 45/1975 [01:28<59:20,  1.84s/it]

Not all axial slices found for 97634230: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

  2%|▏         | 47/1975 [01:32<1:02:43,  1.95s/it]

Not all axial slices found for 105895264: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

  3%|▎         | 51/1975 [01:42<1:17:49,  2.43s/it]

Not all axial slices found for 108348787: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

  4%|▎         | 74/1975 [02:48<1:24:06,  2.65s/it]

Not all axial slices found for 159721286: ['L5/S1' 'L4/L5' 'L3/L4']

  5%|▍         | 93/1975 [03:34<1:11:14,  2.27s/it]

Not all axial slices found for 198104941: ['L5/S1' 'L4/L5' 'L3/L4']

  7%|▋         | 136/1975 [05:39<1:33:29,  3.05s/it]

Not all axial slices found for 293713262: ['L5/S1' 'L4/L5' 'L3/L4']

  7%|▋         | 137/1975 [05:42<1:40:55,  3.29s/it]

Not all axial slices found for 296083289: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

  7%|▋         | 138/1975 [05:45<1:31:00,  2.97s/it]

Not all axial slices found for 296284854: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

  7%|▋         | 142/1975 [05:57<1:27:16,  2.86s/it]

Not all axial slices found for 305320071: ['L5/S1' 'L4/L5' 'L3/L4']

  8%|▊         | 165/1975 [07:16<1:25:47,  2.84s/it]

Not all axial slices found for 344269999: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

  9%|▉         | 173/1975 [07:43<1:22:21,  2.74s/it]

Not all axial slices found for 368848859: ['L5/S1' 'L4/L5' 'L3/L4']

  9%|▉         | 179/1975 [08:06<1:41:31,  3.39s/it]

Not all axial slices found for 376723024: ['L5/S1' 'L4/L5' 'L3/L4']

  9%|▉         | 181/1975 [08:10<1:21:59,  2.74s/it]

Not all axial slices found for 377653138: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

  9%|▉         | 182/1975 [08:12<1:17:06,  2.58s/it]

Not all axial slices found for 379677390: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

  9%|▉         | 186/1975 [08:23<1:17:36,  2.60s/it]

Not all axial slices found for 390498354: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

  9%|▉         | 187/1975 [08:25<1:12:18,  2.43s/it]

Not all axial slices found for 391103067: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 10%|▉         | 188/1975 [08:26<1:06:40,  2.24s/it]

Not all axial slices found for 395898502: ['L5/S1' 'L4/L5' 'L3/L4']

 10%|▉         | 191/1975 [08:35<1:20:07,  2.69s/it]

Not all axial slices found for 404602713: ['L5/S1' 'L4/L5' 'L3/L4']

 10%|▉         | 193/1975 [08:40<1:13:31,  2.48s/it]

Not all axial slices found for 409514453: ['L5/S1' 'L4/L5' 'L3/L4']

 10%|█         | 200/1975 [09:00<1:15:31,  2.55s/it]

Not all axial slices found for 427598893: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 10%|█         | 204/1975 [09:16<1:35:53,  3.25s/it]

Not all axial slices found for 434488359: ['L5/S1' 'L4/L5' 'L3/L4']

 11%|█         | 210/1975 [09:39<1:50:39,  3.76s/it]

Not all axial slices found for 443364658: ['L5/S1' 'L4/L5' 'L3/L4']

 11%|█         | 216/1975 [09:58<1:30:51,  3.10s/it]

Not all axial slices found for 455813081: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 11%|█▏        | 223/1975 [10:23<1:36:29,  3.30s/it]

Not all axial slices found for 480042730: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 13%|█▎        | 249/1975 [11:56<1:39:29,  3.46s/it]

Not all axial slices found for 532925408: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 13%|█▎        | 264/1975 [12:53<1:48:48,  3.82s/it]

Not all axial slices found for 597329259: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 15%|█▍        | 290/1975 [14:13<1:49:19,  3.89s/it]

Not all axial slices found for 647348777: ['L5/S1' 'L4/L5' 'L3/L4']

 15%|█▍        | 293/1975 [14:22<1:34:47,  3.38s/it]

Not all axial slices found for 652321402: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 15%|█▌        | 302/1975 [14:55<1:28:42,  3.18s/it]

Not all axial slices found for 676719753: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 16%|█▌        | 310/1975 [15:26<1:42:03,  3.68s/it]

Not all axial slices found for 684790345: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 16%|█▌        | 315/1975 [15:47<1:46:33,  3.85s/it]

Not all axial slices found for 693432872: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 19%|█▊        | 367/1975 [18:17<1:18:45,  2.94s/it]

Not all axial slices found for 808539750: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 19%|█▉        | 371/1975 [18:32<1:24:12,  3.15s/it]

Not all axial slices found for 815315878: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 19%|█▉        | 373/1975 [18:37<1:16:13,  2.86s/it]

Not all axial slices found for 823937142: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 19%|█▉        | 385/1975 [19:08<1:06:22,  2.51s/it]

Not all axial slices found for 858422574: ['L5/S1' 'L4/L5' 'L3/L4']

 20%|██        | 402/1975 [20:08<1:29:17,  3.41s/it]

Not all axial slices found for 893250212: ['L5/S1' 'L4/L5' 'L3/L4']

 21%|██        | 405/1975 [20:19<1:28:21,  3.38s/it]

Not all axial slices found for 901299313: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 21%|██        | 412/1975 [20:44<1:22:09,  3.15s/it]

Not all axial slices found for 916362094: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 21%|██        | 413/1975 [20:46<1:17:51,  2.99s/it]

Not all axial slices found for 919752232: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 21%|██        | 416/1975 [20:56<1:19:31,  3.06s/it]

Not all axial slices found for 933559951: ['L5/S1' 'L4/L5' 'L3/L4']

 21%|██        | 419/1975 [21:07<1:26:23,  3.33s/it]

Not all axial slices found for 934686772: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 22%|██▏       | 434/1975 [21:48<1:15:20,  2.93s/it]

Not all axial slices found for 953639220: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 23%|██▎       | 445/1975 [22:23<1:20:24,  3.15s/it]

Not all axial slices found for 975569097: ['L5/S1' 'L4/L5' 'L3/L4']

 23%|██▎       | 456/1975 [22:58<1:18:52,  3.12s/it]

Not all axial slices found for 998688940: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 24%|██▍       | 475/1975 [23:59<1:09:00,  2.76s/it]

Not all axial slices found for 1040921274: ['L5/S1' 'L4/L5' 'L3/L4']

 24%|██▍       | 476/1975 [24:02<1:15:58,  3.04s/it]

Not all axial slices found for 1047914296: ['L5/S1' 'L4/L5' 'L3/L4']

 24%|██▍       | 477/1975 [24:05<1:12:30,  2.90s/it]

Not all axial slices found for 1050200728: ['L5/S1' 'L4/L5' 'L3/L4']

 25%|██▌       | 495/1975 [25:02<1:25:13,  3.46s/it]

Not all axial slices found for 1094879459: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 25%|██▌       | 496/1975 [25:06<1:29:35,  3.63s/it]

Not all axial slices found for 1095894979: ['L5/S1' 'L4/L5' 'L3/L4']

 25%|██▌       | 500/1975 [25:15<58:59,  2.40s/it]

Not all axial slices found for 1103373889: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 25%|██▌       | 503/1975 [25:26<1:16:04,  3.10s/it]

Not all axial slices found for 1106510276: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 26%|██▌       | 513/1975 [25:56<1:04:33,  2.65s/it]

Not all axial slices found for 1125872530: ['L5/S1' 'L4/L5' 'L3/L4']

 26%|██▌       | 518/1975 [26:11<1:06:44,  2.75s/it]

Not all axial slices found for 1133158151: ['L5/S1' 'L4/L5' 'L3/L4']

 27%|██▋       | 532/1975 [26:53<1:14:49,  3.11s/it]

Not all axial slices found for 1169119083: ['L5/S1' 'L4/L5' 'L3/L4']

 27%|██▋       | 540/1975 [27:24<1:39:04,  4.14s/it]

Not all axial slices found for 1187463765: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 28%|██▊       | 545/1975 [27:40<1:21:38,  3.43s/it]

Not all axial slices found for 1199116491: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 29%|██▉       | 581/1975 [29:34<1:01:42,  2.66s/it]

Not all axial slices found for 1278694021: ['L5/S1' 'L4/L5' 'L3/L4']

 30%|██▉       | 586/1975 [29:51<1:15:35,  3.27s/it]

Not all axial slices found for 1292979992: ['L5/S1' 'L4/L5' 'L3/L4']

 30%|███       | 594/1975 [30:15<1:01:30,  2.67s/it]

Not all axial slices found for 1302724340: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 31%|███       | 603/1975 [30:40<59:47,  2.62s/it]

Not all axial slices found for 1332176994: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 31%|███       | 609/1975 [30:58<1:06:09,  2.91s/it]

Not all axial slices found for 1344807906: ['L5/S1' 'L4/L5' 'L3/L4']

 31%|███▏      | 620/1975 [31:30<1:05:19,  2.89s/it]

Not all axial slices found for 1375057718: ['L5/S1' 'L4/L5' 'L3/L4']

 32%|███▏      | 631/1975 [32:03<1:02:53,  2.81s/it]

Not all axial slices found for 1395773918: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 32%|███▏      | 637/1975 [32:22<1:10:24,  3.16s/it]

Not all axial slices found for 1414872844: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 32%|███▏      | 639/1975 [32:29<1:18:05,  3.51s/it]

Not all axial slices found for 1417061937: ['L5/S1' 'L4/L5' 'L3/L4']

 32%|███▏      | 640/1975 [32:30<1:04:43,  2.91s/it]

Not all axial slices found for 1418464479: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 33%|███▎      | 642/1975 [32:38<1:13:19,  3.30s/it]

Not all axial slices found for 1422523769: ['L5/S1' 'L4/L5' 'L3/L4']

 33%|███▎      | 643/1975 [32:40<1:05:24,  2.95s/it]

Not all axial slices found for 1423031356: ['L5/S1' 'L4/L5' 'L3/L4']

 33%|███▎      | 646/1975 [32:50<1:10:48,  3.20s/it]

Not all axial slices found for 1425886222: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 33%|███▎      | 648/1975 [32:55<1:02:20,  2.82s/it]

Not all axial slices found for 1431195383: ['L5/S1' 'L4/L5' 'L3/L4']

 33%|███▎      | 658/1975 [33:23<1:00:25,  2.75s/it]

Not all axial slices found for 1451886888: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 33%|███▎      | 660/1975 [33:29<1:04:10,  2.93s/it]

Not all axial slices found for 1452830936: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 33%|███▎      | 661/1975 [33:32<1:01:28,  2.81s/it]

Not all axial slices found for 1456430985: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 34%|███▍      | 670/1975 [34:01<1:06:49,  3.07s/it]

Not all axial slices found for 1472262122: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 34%|███▍      | 681/1975 [34:34<59:26,  2.76s/it]

Not all axial slices found for 1504981676: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 35%|███▍      | 684/1975 [34:41<47:53,  2.23s/it]

Not all axial slices found for 1510451897: ['L5/S1' 'L4/L5' 'L3/L4']

 35%|███▌      | 694/1975 [35:15<1:18:07,  3.66s/it]

Not all axial slices found for 1531615123: ['L5/S1' 'L4/L5' 'L3/L4']

 36%|███▌      | 703/1975 [35:50<1:20:02,  3.78s/it]

Not all axial slices found for 1545888499: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 36%|███▌      | 705/1975 [35:55<1:10:11,  3.32s/it]

Not all axial slices found for 1546157543: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 36%|███▌      | 709/1975 [36:06<57:16,  2.71s/it]

Not all axial slices found for 1557387235: ['L5/S1' 'L4/L5' 'L3/L4']

 36%|███▌      | 713/1975 [36:17<58:38,  2.79s/it]

Not all axial slices found for 1567179188: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 36%|███▋      | 716/1975 [36:26<1:03:43,  3.04s/it]

Not all axial slices found for 1575827384: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 37%|███▋      | 729/1975 [37:10<1:10:37,  3.40s/it]

Not all axial slices found for 1613634521: ['L5/S1' 'L4/L5' 'L3/L4']

 37%|███▋      | 737/1975 [37:34<59:28,  2.88s/it]

Not all axial slices found for 1641631752: ['L5/S1' 'L4/L5' 'L3/L4']

 38%|███▊      | 744/1975 [37:57<1:09:19,  3.38s/it]

Not all axial slices found for 1650340034: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 38%|███▊      | 745/1975 [38:00<1:05:02,  3.17s/it]

Not all axial slices found for 1651579992: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 38%|███▊      | 756/1975 [38:42<1:15:20,  3.71s/it]

Not all axial slices found for 1671291853: ['L5/S1' 'L4/L5' 'L3/L4']

 39%|███▊      | 761/1975 [39:00<1:09:07,  3.42s/it]

Not all axial slices found for 1678045823: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 39%|███▊      | 763/1975 [39:06<1:01:26,  3.04s/it]

Not all axial slices found for 1681401548: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 39%|███▉      | 767/1975 [39:18<58:43,  2.92s/it]

Not all axial slices found for 1698156042: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 39%|███▉      | 775/1975 [39:41<54:41,  2.73s/it]

Not all axial slices found for 1719776527: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 39%|███▉      | 778/1975 [39:51<59:53,  3.00s/it]

Not all axial slices found for 1722539301: ['L5/S1' 'L4/L5' 'L3/L4']

 40%|███▉      | 784/1975 [40:10<1:01:50,  3.12s/it]

Not all axial slices found for 1734639980: ['L4/L5' 'L3/L4' 'L2/L3' 'L1/L2']

 40%|████      | 791/1975 [40:35<1:06:49,  3.39s/it]

Not all axial slices found for 1748705434: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 40%|████      | 793/1975 [40:43<1:11:00,  3.60s/it]

Not all axial slices found for 1750792644: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 41%|████      | 801/1975 [41:08<1:05:26,  3.34s/it]

Not all axial slices found for 1764741993: ['L5/S1' 'L4/L5' 'L3/L4']

 42%|████▏     | 822/1975 [42:12<1:04:00,  3.33s/it]

Not all axial slices found for 1812655676: ['L5/S1' 'L4/L5' 'L3/L4']

 42%|████▏     | 832/1975 [42:41<46:31,  2.44s/it]

Not all axial slices found for 1833077159: ['L5/S1' 'L4/L5' 'L3/L4']

 43%|████▎     | 848/1975 [43:28<51:51,  2.76s/it]

Not all axial slices found for 1872256708: ['L5/S1' 'L4/L5' 'L3/L4']

 43%|████▎     | 850/1975 [43:33<49:34,  2.64s/it]

Not all axial slices found for 1877684618: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 44%|████▎     | 862/1975 [44:09<53:00,  2.86s/it]

Not all axial slices found for 1900598881: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 44%|████▍     | 875/1975 [45:02<1:00:29,  3.30s/it]

Not all axial slices found for 1934246813: ['L5/S1' 'L4/L5' 'L3/L4']

 45%|████▍     | 882/1975 [45:26<1:03:13,  3.47s/it]

Not all axial slices found for 1956588335: ['L5/S1' 'L4/L5' 'L3/L4']

 45%|████▌     | 894/1975 [46:11<1:17:55,  4.32s/it]

Not all axial slices found for 1983333974: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 45%|████▌     | 896/1975 [46:25<1:43:55,  5.78s/it]

Not all axial slices found for 1992037544: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 46%|████▋     | 916/1975 [47:36<1:10:00,  3.97s/it]

Not all axial slices found for 2028805796: ['L5/S1' 'L4/L5' 'L3/L4']

 47%|████▋     | 922/1975 [47:56<59:17,  3.38s/it]

Not all axial slices found for 2040217841: ['L5/S1' 'L4/L5' 'L3/L4']

 47%|████▋     | 925/1975 [48:04<52:10,  2.98s/it]

Not all axial slices found for 2046176090: ['L5/S1' 'L4/L5' 'L3/L4']

 47%|████▋     | 927/1975 [48:09<48:52,  2.80s/it]

Not all axial slices found for 2048265504: ['L4/L5' 'L3/L4' 'L2/L3' 'L1/L2']

 48%|████▊     | 950/1975 [49:15<36:59,  2.17s/it]

Not all axial slices found for 2109263401: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 49%|████▊     | 961/1975 [49:49<45:35,  2.70s/it]

Not all axial slices found for 2137189898: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 49%|████▉     | 965/1975 [50:00<47:19,  2.81s/it]

Not all axial slices found for 2139301976: ['L5/S1' 'L4/L5' 'L3/L4']

 49%|████▉     | 976/1975 [50:31<51:19,  3.08s/it]

Not all axial slices found for 2168331230: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 50%|████▉     | 978/1975 [50:36<44:47,  2.70s/it]

Not all axial slices found for 2172940318: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 50%|█████     | 990/1975 [51:11<42:46,  2.61s/it]

Not all axial slices found for 2200084279: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 50%|█████     | 994/1975 [51:24<47:00,  2.87s/it]

Not all axial slices found for 2213304029: ['L5/S1' 'L4/L5' 'L3/L4']

 51%|█████     | 1000/1975 [51:46<56:26,  3.47s/it]

Not all axial slices found for 2232794498: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 51%|█████     | 1004/1975 [51:56<46:19,  2.86s/it]

Not all axial slices found for 2239199413: ['L5/S1' 'L4/L5' 'L3/L4']

 51%|█████▏    | 1014/1975 [52:27<50:58,  3.18s/it]

Not all axial slices found for 2256339732: ['L5/S1' 'L4/L5' 'L3/L4']

 52%|█████▏    | 1024/1975 [53:03<1:11:11,  4.49s/it]

Not all axial slices found for 2279142182: ['L5/S1' 'L4/L5' 'L3/L4']

 52%|█████▏    | 1036/1975 [53:42<45:59,  2.94s/it]

Not all axial slices found for 2297295777: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 53%|█████▎    | 1044/1975 [54:08<49:04,  3.16s/it]

Not all axial slices found for 2323872325: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 53%|█████▎    | 1052/1975 [54:39<56:57,  3.70s/it]

Not all axial slices found for 2336355021: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 53%|█████▎    | 1053/1975 [54:43<55:08,  3.59s/it]

Not all axial slices found for 2336516775: ['L5/S1' 'L4/L5' 'L3/L4']

 54%|█████▎    | 1061/1975 [55:07<48:04,  3.16s/it]

Not all axial slices found for 2351425784: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 54%|█████▍    | 1065/1975 [55:21<47:09,  3.11s/it]

Not all axial slices found for 2361404807: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 55%|█████▍    | 1079/1975 [55:59<44:39,  2.99s/it]

Not all axial slices found for 2388577668: []

 55%|█████▍    | 1080/1975 [56:02<43:42,  2.93s/it]

Not all axial slices found for 2392247193: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 55%|█████▍    | 1084/1975 [56:15<45:13,  3.05s/it]

Not all axial slices found for 2397650165: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 55%|█████▌    | 1087/1975 [56:23<43:40,  2.95s/it]

Not all axial slices found for 2406108213: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 55%|█████▌    | 1095/1975 [56:48<45:21,  3.09s/it]

Not all axial slices found for 2427880799: ['L5/S1' 'L4/L5' 'L3/L4']

 56%|█████▌    | 1101/1975 [57:05<44:00,  3.02s/it]

Not all axial slices found for 2438880310: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 56%|█████▌    | 1108/1975 [57:29<41:33,  2.88s/it]

Not all axial slices found for 2449094561: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 57%|█████▋    | 1118/1975 [58:01<41:11,  2.88s/it]

Not all axial slices found for 2477309406: ['L5/S1' 'L4/L5' 'L3/L4']

 57%|█████▋    | 1124/1975 [58:15<32:31,  2.29s/it]

Not all axial slices found for 2490271413: ['L5/S1' 'L4/L5' 'L3/L4']

 57%|█████▋    | 1129/1975 [58:31<43:31,  3.09s/it]

Not all axial slices found for 2493610993: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 57%|█████▋    | 1133/1975 [58:44<46:20,  3.30s/it]

Not all axial slices found for 2498439772: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 57%|█████▋    | 1135/1975 [58:51<48:11,  3.44s/it]

Not all axial slices found for 2504110412: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 58%|█████▊    | 1142/1975 [59:16<42:23,  3.05s/it]

Not all axial slices found for 2513871828: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 58%|█████▊    | 1145/1975 [59:24<38:52,  2.81s/it]

Not all axial slices found for 2528047920: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 58%|█████▊    | 1155/1975 [59:58<36:59,  2.71s/it]

Not all axial slices found for 2541987714: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 59%|█████▊    | 1158/1975 [1:00:06<37:46,  2.77s/it]

Not all axial slices found for 2548543893: ['L5/S1' 'L4/L5' 'L3/L4']

 59%|█████▊    | 1159/1975 [1:00:08<34:41,  2.55s/it]

Not all axial slices found for 2550694704: ['L5/S1' 'L4/L5' 'L3/L4']

 59%|█████▉    | 1166/1975 [1:00:34<49:03,  3.64s/it]

Not all axial slices found for 2563313484: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 59%|█████▉    | 1168/1975 [1:00:38<38:33,  2.87s/it]

Not all axial slices found for 2566719718: ['L5/S1' 'L4/L5' 'L3/L4']

 59%|█████▉    | 1170/1975 [1:00:46<44:12,  3.29s/it]

Not all axial slices found for 2569123363: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 60%|█████▉    | 1184/1975 [1:01:27<33:04,  2.51s/it]

Not all axial slices found for 2597449301: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 60%|██████    | 1193/1975 [1:01:54<43:04,  3.31s/it]

Not all axial slices found for 2615694902: ['L5/S1' 'L4/L5' 'L3/L4']

 61%|██████    | 1198/1975 [1:02:07<32:07,  2.48s/it]

Not all axial slices found for 2621647501: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 61%|██████    | 1208/1975 [1:02:39<37:37,  2.94s/it]

Not all axial slices found for 2638691430: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 62%|██████▏   | 1218/1975 [1:03:08<37:39,  2.98s/it]

Not all axial slices found for 2662989538: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 62%|██████▏   | 1220/1975 [1:03:13<33:37,  2.67s/it]

Not all axial slices found for 2669990440: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 62%|██████▏   | 1223/1975 [1:03:21<32:15,  2.57s/it]

Not all axial slices found for 2681235806: ['L5/S1' 'L4/L5' 'L3/L4']

 63%|██████▎   | 1236/1975 [1:03:58<32:05,  2.61s/it]

Not all axial slices found for 2713141511: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 63%|██████▎   | 1252/1975 [1:04:40<35:07,  2.91s/it]

Not all axial slices found for 2742959081: ['L5/S1' 'L4/L5' 'L3/L4']

 64%|██████▍   | 1266/1975 [1:05:22<35:17,  2.99s/it]

Not all axial slices found for 2767664103: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 65%|██████▌   | 1285/1975 [1:06:14<33:24,  2.91s/it]

Not all axial slices found for 2799503775: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 66%|██████▌   | 1299/1975 [1:06:55<37:49,  3.36s/it]

Not all axial slices found for 2820783595: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 66%|██████▌   | 1306/1975 [1:07:16<34:01,  3.05s/it]

Not all axial slices found for 2839003053: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 67%|██████▋   | 1322/1975 [1:08:05<30:38,  2.82s/it]

Not all axial slices found for 2878059176: ['L5/S1' 'L4/L5' 'L3/L4']

 67%|██████▋   | 1326/1975 [1:08:18<35:13,  3.26s/it]

Not all axial slices found for 2883475064: ['L5/S1' 'L4/L5' 'L3/L4']

 67%|██████▋   | 1333/1975 [1:08:44<38:19,  3.58s/it]

Not all axial slices found for 2905025904: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 68%|██████▊   | 1336/1975 [1:08:54<36:01,  3.38s/it]

Not all axial slices found for 2907745008: ['L5/S1' 'L4/L5' 'L3/L4']

 68%|██████▊   | 1342/1975 [1:09:15<34:25,  3.26s/it]

Not all axial slices found for 2918363467: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 68%|██████▊   | 1347/1975 [1:09:30<29:08,  2.78s/it]

Not all axial slices found for 2937573964: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 69%|██████▉   | 1360/1975 [1:10:09<28:13,  2.75s/it]

Not all axial slices found for 2958761272: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 69%|██████▉   | 1363/1975 [1:10:19<31:46,  3.11s/it]

Not all axial slices found for 2966999234: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 70%|███████   | 1384/1975 [1:11:19<25:56,  2.63s/it]

Not all axial slices found for 3016102133: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 70%|███████   | 1386/1975 [1:11:27<32:58,  3.36s/it]

Not all axial slices found for 3018856000: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 70%|███████   | 1390/1975 [1:11:38<31:49,  3.26s/it]

Not all axial slices found for 3029953735: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 71%|███████   | 1398/1975 [1:12:04<32:00,  3.33s/it]

Not all axial slices found for 3046761065: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 71%|███████   | 1404/1975 [1:12:22<28:46,  3.02s/it]

Not all axial slices found for 3060042925: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 72%|███████▏  | 1413/1975 [1:12:46<22:26,  2.40s/it]

Not all axial slices found for 3084269121: ['L5/S1' 'L4/L5' 'L3/L4']

 72%|███████▏  | 1423/1975 [1:13:18<30:45,  3.34s/it]

Not all axial slices found for 3109648055: ['L5/S1' 'L4/L5' 'L3/L4']

 73%|███████▎  | 1433/1975 [1:13:50<28:05,  3.11s/it]

Not all axial slices found for 3133422961: ['L5/S1' 'L4/L5' 'L3/L4']

 73%|███████▎  | 1435/1975 [1:13:56<28:32,  3.17s/it]

Not all axial slices found for 3138807119: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 73%|███████▎  | 1438/1975 [1:14:06<29:43,  3.32s/it]

Not all axial slices found for 3141331592: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 73%|███████▎  | 1441/1975 [1:14:13<23:59,  2.70s/it]

Not all axial slices found for 3151371929: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 74%|███████▎  | 1454/1975 [1:14:55<30:09,  3.47s/it]

Not all axial slices found for 3167888497: ['L5/S1' 'L4/L5' 'L3/L4']

 74%|███████▎  | 1455/1975 [1:14:59<31:07,  3.59s/it]

Not all axial slices found for 3168755174: ['L5/S1' 'L4/L5' 'L3/L4']

 74%|███████▍  | 1462/1975 [1:15:25<31:20,  3.67s/it]

Not all axial slices found for 3187370039: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 74%|███████▍  | 1464/1975 [1:15:31<30:06,  3.54s/it]

Not all axial slices found for 3189076268: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 75%|███████▌  | 1482/1975 [1:16:27<23:07,  2.81s/it]

Not all axial slices found for 3221995449: ['L5/S1' 'L4/L5' 'L3/L4']

 76%|███████▌  | 1497/1975 [1:17:16<24:31,  3.08s/it]

Not all axial slices found for 3252162306: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 76%|███████▌  | 1499/1975 [1:17:21<22:10,  2.79s/it]

Not all axial slices found for 3260381770: ['L5/S1' 'L4/L5' 'L3/L4']

 77%|███████▋  | 1516/1975 [1:18:16<23:32,  3.08s/it]

Not all axial slices found for 3301026080: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 77%|███████▋  | 1517/1975 [1:18:18<22:08,  2.90s/it]

Not all axial slices found for 3303545110: ['L5/S1' 'L4/L5']

 77%|███████▋  | 1520/1975 [1:18:27<22:30,  2.97s/it]

Not all axial slices found for 3304253168: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 77%|███████▋  | 1521/1975 [1:18:30<20:45,  2.74s/it]

Not all axial slices found for 3304686512: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 77%|███████▋  | 1523/1975 [1:18:36<22:03,  2.93s/it]

Not all axial slices found for 3308442440: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 77%|███████▋  | 1528/1975 [1:18:52<24:53,  3.34s/it]

Not all axial slices found for 3319644132: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 79%|███████▉  | 1567/1975 [1:20:54<16:35,  2.44s/it]

Not all axial slices found for 3412978571: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 79%|███████▉  | 1569/1975 [1:20:59<17:40,  2.61s/it]

Not all axial slices found for 3421079924: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 80%|███████▉  | 1577/1975 [1:21:29<20:54,  3.15s/it]

Not all axial slices found for 3428426893: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 81%|████████  | 1594/1975 [1:22:21<17:07,  2.70s/it]

Not all axial slices found for 3469376405: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 81%|████████  | 1595/1975 [1:22:23<15:59,  2.53s/it]

Not all axial slices found for 3472609688: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 82%|████████▏ | 1620/1975 [1:23:46<18:57,  3.20s/it]

Not all axial slices found for 3507232306: ['L5/S1' 'L4/L5' 'L3/L4']

 82%|████████▏ | 1623/1975 [1:24:00<24:45,  4.22s/it]

Not all axial slices found for 3515641631: ['L5/S1' 'L4/L5' 'L3/L4']

 82%|████████▏ | 1625/1975 [1:24:08<23:41,  4.06s/it]

Not all axial slices found for 3521369408: ['L5/S1' 'L4/L5' 'L3/L4']

 82%|████████▏ | 1627/1975 [1:24:16<23:29,  4.05s/it]

Not all axial slices found for 3525503074: ['L5/S1' 'L4/L5' 'L3/L4' 'L1/L2']

 83%|████████▎ | 1633/1975 [1:24:35<18:34,  3.26s/it]

Not all axial slices found for 3534804406: ['L5/S1' 'L4/L5' 'L3/L4']

 83%|████████▎ | 1634/1975 [1:24:39<19:13,  3.38s/it]

Not all axial slices found for 3537214277: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 84%|████████▍ | 1659/1975 [1:26:03<16:22,  3.11s/it]

Not all axial slices found for 3583858507: ['L5/S1' 'L4/L5' 'L3/L4']

 85%|████████▍ | 1669/1975 [1:26:31<14:10,  2.78s/it]

Not all axial slices found for 3617698707: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 85%|████████▍ | 1677/1975 [1:26:52<13:16,  2.67s/it]

Not all axial slices found for 3646569986: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 85%|████████▌ | 1686/1975 [1:27:24<15:19,  3.18s/it]

Not all axial slices found for 3668205319: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 85%|████████▌ | 1688/1975 [1:27:30<14:29,  3.03s/it]

Not all axial slices found for 3674744025: ['L5/S1' 'L4/L5' 'L3/L4']

 86%|████████▌ | 1693/1975 [1:27:46<15:24,  3.28s/it]

Not all axial slices found for 3685379620: ['L5/S1' 'L4/L5' 'L3/L4']

 87%|████████▋ | 1709/1975 [1:28:42<15:44,  3.55s/it]

Not all axial slices found for 3711891194: ['L5/S1' 'L4/L5' 'L3/L4']

 87%|████████▋ | 1710/1975 [1:28:45<15:23,  3.48s/it]

Not all axial slices found for 3713534743: ['L5/S1' 'L4/L5' 'L3/L4']

 87%|████████▋ | 1727/1975 [1:29:38<13:52,  3.36s/it]

Not all axial slices found for 3745670967: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 88%|████████▊ | 1737/1975 [1:30:13<13:03,  3.29s/it]

Not all axial slices found for 3771340895: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 89%|████████▊ | 1752/1975 [1:31:02<10:50,  2.92s/it]

Not all axial slices found for 3824720894: ['L5/S1' 'L4/L5' 'L3/L4']

 89%|████████▉ | 1753/1975 [1:31:04<09:56,  2.69s/it]

Not all axial slices found for 3828017267: ['L5/S1' 'L4/L5' 'L3/L4']

 89%|████████▉ | 1758/1975 [1:31:18<09:07,  2.52s/it]

Not all axial slices found for 3836739612: ['L5/S1' 'L4/L5' 'L3/L4']

 89%|████████▉ | 1766/1975 [1:31:46<12:27,  3.58s/it]

Not all axial slices found for 3850173026: ['L5/S1' 'L4/L5' 'L3/L4']

 89%|████████▉ | 1767/1975 [1:31:48<10:53,  3.14s/it]

Not all axial slices found for 3850799893: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 91%|█████████ | 1798/1975 [1:33:37<09:56,  3.37s/it]

Not all axial slices found for 3892114403: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 92%|█████████▏| 1814/1975 [1:34:38<08:24,  3.13s/it]

Not all axial slices found for 3936691827: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 92%|█████████▏| 1823/1975 [1:35:08<08:40,  3.42s/it]

Not all axial slices found for 3951588890: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 92%|█████████▏| 1824/1975 [1:35:11<08:33,  3.40s/it]

Not all axial slices found for 3952663938: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 93%|█████████▎| 1827/1975 [1:35:25<09:44,  3.95s/it]

Not all axial slices found for 3959198150: ['L5/S1' 'L4/L5' 'L3/L4']

 93%|█████████▎| 1829/1975 [1:35:36<11:49,  4.86s/it]

Not all axial slices found for 3966998094: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 93%|█████████▎| 1835/1975 [1:35:53<07:02,  3.02s/it]

Not all axial slices found for 3973705542: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 93%|█████████▎| 1836/1975 [1:35:55<06:47,  2.93s/it]

Not all axial slices found for 3976403280: ['L5/S1' 'L4/L5' 'L3/L4']

 93%|█████████▎| 1838/1975 [1:36:01<06:30,  2.85s/it]

Not all axial slices found for 3985606537: ['L5/S1' 'L4/L5' 'L3/L4']

 94%|█████████▍| 1852/1975 [1:36:57<10:22,  5.06s/it]

Not all axial slices found for 4024872715: ['L5/S1' 'L4/L5' 'L3/L4']

 94%|█████████▍| 1860/1975 [1:37:23<05:36,  2.93s/it]

Not all axial slices found for 4050147189: ['L5/S1' 'L4/L5' 'L3/L4']

 95%|█████████▍| 1871/1975 [1:37:59<05:04,  2.93s/it]

Not all axial slices found for 4071042236: ['L5/S1' 'L4/L5' 'L3/L4']

 95%|█████████▍| 1874/1975 [1:38:07<04:50,  2.87s/it]

Not all axial slices found for 4072455711: ['L5/S1' 'L4/L5' 'L3/L4']

 96%|█████████▌| 1891/1975 [1:39:05<04:13,  3.02s/it]

Not all axial slices found for 4114864639: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 96%|█████████▌| 1896/1975 [1:39:22<03:58,  3.02s/it]

Not all axial slices found for 4123072754: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 96%|█████████▌| 1900/1975 [1:39:35<03:57,  3.16s/it]

Not all axial slices found for 4127969449: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 96%|█████████▋| 1904/1975 [1:39:45<03:09,  2.67s/it]

Not all axial slices found for 4137194670: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 97%|█████████▋| 1906/1975 [1:39:56<04:42,  4.10s/it]

Not all axial slices found for 4140710202: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 97%|█████████▋| 1912/1975 [1:40:14<03:08,  2.99s/it]

Not all axial slices found for 4146959702: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 98%|█████████▊| 1926/1975 [1:41:07<03:07,  3.83s/it]

Not all axial slices found for 4175603528: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 98%|█████████▊| 1935/1975 [1:41:35<02:01,  3.03s/it]

Not all axial slices found for 4200324709: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 98%|█████████▊| 1940/1975 [1:41:51<01:48,  3.09s/it]

Not all axial slices found for 4219508579: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 99%|█████████▉| 1951/1975 [1:42:28<01:29,  3.72s/it]

Not all axial slices found for 4232806580: ['L5/S1' 'L4/L5' 'L3/L4']

 99%|█████████▉| 1953/1975 [1:42:34<01:16,  3.47s/it]

Not all axial slices found for 4238265702: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

 99%|█████████▉| 1959/1975 [1:42:52<00:46,  2.88s/it]

Not all axial slices found for 4255570773: ['L5/S1' 'L4/L5' 'L3/L4' 'L2/L3']

100%|██████████| 1975/1975 [1:43:58<00:00,  3.16s/it]

In [15]:
# Plot all BBs
# plotImageWithBB(im.detach().cpu().numpy()[0,:,:], [torch.tensor(filteredBoundingBoxes[el]["filteredBB"]) for el in ALL_CLASSES], torch.tensor([0,1,1,1,1]))

# Plot current BB
# plotImageWithBB(im.detach().cpu()[0,:,:], torch.tensor([bb]))

#Visualize 3D world
# Visualize3DPointsAndSlices([[startPos],[endPos], [s.getWorldPosition(s.data.shape[0]//2, s.data.shape[1]//2) for s in patData.getAxialScans()[0].slices]], sliceList=patData.getAxialScans()[0].slices)

In [ ]:
testStudyId = list(allData.keys())[12]
testData = allData[list(allData.keys())[12]]
print(testStudyId)

In [ ]:
Visualize3DPointsAndSlices([allPoints[testStudyId]["axialPoints"], allPoints[testStudyId]["sagittalPoints"]])

In [ ]:
numIm = int(np.ceil(np.sqrt(len(testData["sagittalPatches"]["L5/S1"]))))
for i,im in enumerate(testData["sagittalPatches"]["L5/S1"]):
    plt.subplot(numIm, numIm, i+1)
    plt.imshow(im)
    plt.axis("off")

In [ ]:
testData["axSlices"]

In [ ]:
for c in ALL_CLASSES:
    print(c)
    testData["axSlices"][c][0][0].plot()

In [23]:
from scipy.ndimage import zoom
from PIL import Image

def plotMriVolume(slices):
    im=Image.fromarray(slices[0].data)
    xCount = int(slices[0].data.shape[0]*0.1)
    yCount = int(slices[0].data.shape[1]*0.1)
    im = im.resize(( xCount, yCount ))
    # Calculate the extent of the volume in millimeters
    zCount = len(slices)

    X, Y, Z = np.mgrid[0:xCount, 0:yCount, 0:zCount]

    # Initialize the volume with zeros
    volume = np.zeros((xCount,yCount,zCount), dtype=np.float32)
    
    for i, s in enumerate(slices):
        im=Image.fromarray(s.data)
        im = im.resize(( xCount, yCount ))
        # Insert the slice into the volume
        volume[:,:,i] = np.array(im)
    
    # Normalize the volume data
    # volume = (volume - np.min(volume)) / (np.max(volume) - np.min(volume))
    
    # Create a 3D volume plot
    fig = go.Figure(data=go.Volume(
        x=X.flatten(),
        y=Y.flatten(),
        z=Z.flatten(),
        value=volume.flatten(),
        opacity=0.5,
        surface_count=25,
        colorscale='Gray'
    ))

    print(volume.flatten().shape)

    # Set the correct axis labels and ranges
    fig.update_layout(scene=dict(
        xaxis=dict(range=[0, xCount], title='X (mm)'),
        yaxis=dict(range=[0, yCount], title='Y (mm)'),
        zaxis=dict(range=[0, zCount], title='Z (mm)')
    ))
    
    pio.show(fig)


# plotMriVolume(patData.getAxialScans()[0].slices)